"""Initial schema creation

Revision ID: 707bbe04f7f7
Revises: 
Create Date: 2025-12-16 19:30:26.416226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707bbe04f7f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'log_details')
    op.drop_column('audit_logs', 'resource')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('log_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    # ### end Alembic commands ###
